// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whazqibezrvxzkqwzsts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoYXpxaWJlenJ2eHprcXd6c3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMDUxODQsImV4cCI6MjA1NzU4MTE4NH0.Z9XyzKIWIjGHMvl97QIOFcPMm4GXqTjUirEDbal-eUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);